[build]
  command = "yarn build"

[context.production]
  command = "yarn build"

[[redirects]]
  from = "/startups"
  to = "/delivery"
  status = 301
  force = false

[[redirects]]
  from = "/about"
  to = "/team"
  status = 301
  force = false

[[redirects]]
  from = "/posts/*"
  to = "/blog/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/blog/posts/*"
  to = "/blog/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/yada/*"
  to = "https://github.com/juxt/yada"
  status = 301
  force = false

[[redirects]]
  from = "/yada"
  to = "https://github.com/juxt/yada" 
  status = 301
  force = false

[[redirects]]
  from = "/tick/*"
  to = "https://juxt.github.io/tick/"
  status = 301
  force = false

[[redirects]]
  from = "/edge"
  to = "https://github.com/juxt/edge" 
  status = 301
  force = false 

[[redirects]]
  from = "/crux"
  to = "https://opencrux.com" 
  status = 301
  force = false 

[[redirects]]
  from = "/crux/*"
  to = "https://opencrux.com" 
  status = 301
  force = false 
